import assert from 'node:assert/strict';
import test from 'node:test';
import type {AuthorAnswer} from './author-corpus';
import {AuthorToolSession,parseAuthorToolDecision,MAX_TOOL_CALLS,type AuthorToolResult} from './author-tools';

const answer:AuthorAnswer={
  answerId:'1001',authorName:'合成测试作者',authorUrlToken:'MarryMea',
  authorProfileUrl:'https://www.zhihu.com/people/MarryMea',
  questionTitle:'远程工作如何减少孤独',sourceUrl:'https://www.zhihu.com/answer/1001',
  body:'合成测试：远程工作需要明确休息安排。\n合成测试：孤独时可以安排定期交流。',
  completeness:'stored_body_unverified_against_live_page',
};
const other:AuthorAnswer={...answer,answerId:'2002',authorUrlToken:'other-author',authorName:'另一位作者',questionTitle:'远程工作心得',body:'远程工作远程工作远程工作远程工作'};
const session=()=>new AuthorToolSession([other,answer],'MarryMea');
const decision=(raw:unknown)=>parseAuthorToolDecision(JSON.stringify(raw));

function toolError(result:AuthorToolResult){
  if(result.ok)throw new Error('expected tool error');
  return result.error as {code:string;message:string};
}
function toolData(result:AuthorToolResult){
  if(!result.ok)throw new Error(`expected tool data, got ${result.error.code}`);
  return result.data;
}

test('tool decisions require the strict contract and reject free-form arguments',()=>{
  assert.equal(decision({tool:'search_corpus',args:{query:'远程工作'}}).tool,'search_corpus');
  assert.equal(decision({tool:'read_answer',args:{answerId:'1001'}}).tool,'read_answer');
  assert.equal(decision({tool:'finish',args:{text:'合成回复',citationIds:['1001:p1']}}).tool,'finish');
  assert.throws(()=>decision({tool:'search_corpus',args:{query:'远程工作',path:'/etc/passwd'}}),/工具调用/);
  assert.throws(()=>decision({tool:'read_answer',args:{answerId:'../secret'}}),/工具调用/);
  assert.throws(()=>decision({tool:'delete_corpus',args:{}}),/工具调用/);
  assert.throws(()=>parseAuthorToolDecision('不是 JSON'),/JSON/);
});

test('search stays inside the bound author and returns excerpts, never whole bodies',()=>{
  const tools=session();
  const data=toolData(tools.execute(decision({tool:'search_corpus',args:{query:'远程工作'}}))) as {status:string;items:{id:string;answerId:string;excerpt:string}[]};
  assert.equal(data.status,'matched');
  assert.ok(data.items.length>0);
  assert.ok(data.items.every(item=>item.answerId==='1001'));
  assert.ok(data.items.every(item=>item.excerpt.length<=160));
  assert.ok(!JSON.stringify(data).includes(answer.body));
});

test('search with no lexical match reports no-match instead of random evidence',()=>{
  const tools=session();
  const data=toolData(tools.execute(decision({tool:'search_corpus',args:{query:'量子引力黑洞'}}))) as {status:string};
  assert.equal(data.status,'no-match');
  assert.deepEqual(tools.allowedEvidence,[]);
});

test('read_answer is limited to answers returned by the current search round',()=>{
  const blocked=new AuthorToolSession([other,answer],'MarryMea');
  assert.equal(toolError(blocked.execute(decision({tool:'read_answer',args:{answerId:'1001'}}))).code,'ANSWER_NOT_SEARCHED');
  const tools=session();
  tools.execute(decision({tool:'search_corpus',args:{query:'远程工作'}}));
  const data=toolData(tools.execute(decision({tool:'read_answer',args:{answerId:'1001'}}))) as {paragraphs:{id:string;text:string}[]};
  assert.deepEqual(data.paragraphs.map(item=>item.id),['1001:p1','1001:p2']);
  assert.ok(tools.allowedEvidence.every(item=>item.answerId==='1001'));
});

test('citations must come from this round and links are generated by the app',()=>{
  const tools=session();
  assert.equal(toolError(tools.execute(decision({tool:'finish',args:{text:'引用不存在',citationIds:['fake:p1']}}))).code,'CITATION_OUT_OF_RANGE');
  tools.execute(decision({tool:'search_corpus',args:{query:'远程工作'}}));
  const data=toolData(tools.execute(decision({tool:'finish',args:{text:'合成回复',citationIds:['1001:p1']}}))) as {sources:{url:string;answerId:string}[]};
  assert.deepEqual(data.sources.map(source=>source.answerId),['1001']);
  assert.equal(data.sources[0].url,'https://www.zhihu.com/answer/1001');
  tools.execute(decision({tool:'search_corpus',args:{query:'远程工作'}}));
  assert.equal(toolError(tools.execute(decision({tool:'finish',args:{text:'见 https://evil.test',citationIds:['1001:p1']}}))).code,'INVALID_REPLY_TEXT');
});

test('tool calls are capped but a valid finish is always allowed',()=>{
  const tools=session();
  tools.execute(decision({tool:'search_corpus',args:{query:'远程工作'}}));
  tools.execute(decision({tool:'read_answer',args:{answerId:'1001'}}));
  assert.equal(tools.toolCalls,MAX_TOOL_CALLS);
  assert.equal(toolError(tools.execute(decision({tool:'search_corpus',args:{query:'远程工作'}}))).code,'TOOL_BUDGET_EXCEEDED');
  assert.ok(tools.execute(decision({tool:'finish',args:{text:'合成回复',citationIds:['1001:p1']}})).ok);
});

test('oversized evidence fails explicitly instead of being silently truncated',()=>{
  const huge:AuthorAnswer={...answer,body:'远程工作'.repeat(1200)};
  const tools=new AuthorToolSession([huge],'MarryMea');
  assert.equal(toolError(tools.execute(decision({tool:'search_corpus',args:{query:'远程工作'}}))).code,'EVIDENCE_TOO_LARGE');
});
